### ISSUE TITLE
undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by mhumeSF** [wkoszek/lastpass-ssh#8]
I am unable to run lastpass-ssh. Is there a specific ruby version this is required to run with?

```
$ lastpass-ssh

Traceback (most recent call last):
	2: from /usr/local/bin/lastpass-ssh:23:in `<main>'
	1: from /usr/local/bin/lastpass-ssh:23:in `load'
/usr/local/lib/ruby/gems/2.5.0/gems/lastpass-ssh-1.0.4/bin/lastpass-ssh:65:in `<top (required)>': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by wkoszek** [comment]
@mhumeSF First: thanks for the report. The problem is with `lastpass-ssh` not handling the error condition well.  I pushed an update into `1.0.6` release, so maybe try to install the latest gem and see if it helped. You should get something a little easier to read on your side.

If it still doesn't work, let's continue debugging together.

**Comment by mhumeSF** [comment]
This looks to be working now, though I had a different thought of what this was used for. This replaces having to use keychain if one was on osx?

**Comment by wkoszek** [comment]
@mhumeSF It'd be helpful for me to understand what you believed the `lastpass-ssh` is for, so that I can understand how to improve the documentation.

Buy yeah: instead of adding an SSH passphrase to macOS keychain, in here, you use Ansible Vault. You unlock its Vault with your password, and inside of the Vault you have pass-phrases to unlock your SSH keys.

**Comment by mhumeSF** [comment]
So I thought this was sort of a tool to migrate ssh-keys from keychain to lastpass. Very cool tool
